# Generated by Django 6.0.4 on 2026-05-12 12:12

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0233_device_render_config_permission'),
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('tenancy', '0024_default_ordering_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FibreLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(default='planned', max_length=32)),
                ('a_termination_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('b_termination_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('connector_loss_db', models.DecimalField(decimal_places=3, default=0.3, max_digits=5)),
                ('connectors_per_end', models.PositiveSmallIntegerField(default=2)),
                ('target_loss_budget_db', models.DecimalField(decimal_places=3, default=10.0, max_digits=6)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('comments', models.TextField(blank=True, default='')),
                ('a_termination_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('b_termination_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Fibre Link',
                'verbose_name_plural': 'Fibre Links',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OspCable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('cid', models.CharField(max_length=64, unique=True)),
                ('type', models.CharField(default='loose-tube-armoured', max_length=32)),
                ('status', models.CharField(default='planned', max_length=32)),
                ('install_method', models.CharField(blank=True, default='', max_length=32)),
                ('fibre_count', models.PositiveSmallIntegerField(default=24)),
                ('tube_count', models.PositiveSmallIntegerField(default=2)),
                ('fibres_per_tube', models.PositiveSmallIntegerField(default=12)),
                ('length_m', models.PositiveIntegerField(blank=True, null=True)),
                ('attenuation_db_per_km', models.DecimalField(decimal_places=3, default=0.22, max_digits=5)),
                ('part_number', models.CharField(blank=True, default='', max_length=64)),
                ('installed_date', models.DateField(blank=True, null=True)),
                ('route', models.JSONField(blank=True, null=True)),
                ('route_length_m', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('comments', models.TextField(blank=True, default='')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='osp_cables', to='dcim.manufacturer')),
                ('site_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='osp_cables_a', to='dcim.site')),
                ('site_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='osp_cables_b', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='osp_cables', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'OSP Cable',
                'verbose_name_plural': 'OSP Cables',
                'ordering': ('cid',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SpliceClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('closure_type', models.CharField(default='dome', max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=64)),
                ('capacity_splices', models.PositiveSmallIntegerField(default=288)),
                ('status', models.CharField(default='planned', max_length=32)),
                ('installed_date', models.DateField(blank=True, null=True)),
                ('location_point', models.JSONField(blank=True, null=True)),
                ('elevation_m', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('comments', models.TextField(blank=True, default='')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='splice_closures', to='dcim.location')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='splice_closures', to='dcim.manufacturer')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='splice_closures', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Splice Closure',
                'verbose_name_plural': 'Splice Closures',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SpliceTray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('number', models.PositiveSmallIntegerField()),
                ('capacity', models.PositiveSmallIntegerField(default=12)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('closure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trays', to='netbox_osp.spliceclosure')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('closure', 'number'),
                'unique_together': {('closure', 'number')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('position', models.PositiveSmallIntegerField()),
                ('color', models.CharField(blank=True, default='', max_length=16)),
                ('status', models.CharField(default='spare', max_length=32)),
                ('a_termination_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('b_termination_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('a_termination_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('b_termination_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strands', to='netbox_osp.ospcable')),
                ('cable_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='osp_strands', to='dcim.cable')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('cable', 'position'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FibreLinkStrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_strands', to='netbox_osp.fibrelink')),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='link_strands', to='netbox_osp.strand')),
            ],
            options={
                'ordering': ('link', 'position'),
                'unique_together': {('link', 'position'), ('link', 'strand')},
            },
        ),
        migrations.AddField(
            model_name='fibrelink',
            name='strands',
            field=models.ManyToManyField(related_name='links', through='netbox_osp.FibreLinkStrand', to='netbox_osp.strand'),
        ),
        migrations.CreateModel(
            name='Tube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('number', models.PositiveSmallIntegerField()),
                ('color', models.CharField(blank=True, default='', max_length=16)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tubes', to='netbox_osp.ospcable')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('cable', 'number'),
                'unique_together': {('cable', 'number')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='strand',
            name='tube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strands', to='netbox_osp.tube'),
        ),
        migrations.CreateModel(
            name='Splice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('position', models.PositiveSmallIntegerField()),
                ('splice_type', models.CharField(default='fusion', max_length=16)),
                ('loss_db', models.DecimalField(decimal_places=3, default=0.1, max_digits=5)),
                ('spliced_date', models.DateField(blank=True, null=True)),
                ('spliced_by', models.CharField(blank=True, default='', max_length=64)),
                ('otdr_trace_url', models.URLField(blank=True, default='')),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splices', to='netbox_osp.splicetray')),
                ('strand_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='splices_a', to='netbox_osp.strand')),
                ('strand_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='splices_b', to='netbox_osp.strand')),
            ],
            options={
                'ordering': ('tray', 'position'),
                'constraints': [models.CheckConstraint(condition=models.Q(('strand_a', models.F('strand_b')), _negated=True), name='splice_no_self_splice')],
                'unique_together': {('tray', 'position')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='strand',
            unique_together={('cable', 'position')},
        ),
    ]
