# Generated by Django 6.0.4 on 2026-05-13.
"""Add FibreTrunk: parent model for multi-fibre rack-to-rack trunks.

PR A of the v0.2.0 cycle. The TrunkBreakout through-table that bridges
to dcim.Cable lands in PR B (migration 0004_trunkbreakout.py).
"""
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0233_device_render_config_permission"),
        ("extras", "0138_customfieldchoiceset_choice_colors"),
        ("tenancy", "0024_default_ordering_indexes"),
        ("netbox_osp", "0002_locationgeo"),
    ]

    operations = [
        migrations.CreateModel(
            name="FibreTrunk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("custom_field_data", models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ("cid", models.CharField(max_length=64, unique=True)),
                ("trunk_type", models.CharField(default="mpo-24", max_length=32)),
                ("fibre_count", models.PositiveSmallIntegerField(default=24)),
                ("length_m", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("status", models.CharField(default="planned", max_length=32)),
                ("route", models.JSONField(blank=True, null=True)),
                ("show_on_map", models.BooleanField(default=True)),
                ("description", models.CharField(blank=True, default="", max_length=200)),
                ("comments", models.TextField(blank=True, default="")),
                ("manufacturer", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="fibre_trunks",
                    to="dcim.manufacturer",
                )),
                ("tenant", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="fibre_trunks",
                    to="tenancy.tenant",
                )),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "Fibre Trunk",
                "verbose_name_plural": "Fibre Trunks",
                "ordering": ("cid",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="fibretrunk",
            constraint=models.CheckConstraint(
                condition=models.Q(fibre_count__gt=0),
                name="fibretrunk_fibre_count_positive",
            ),
        ),
    ]
