# Generated by Django 6.0.4 on 2026-05-13.
"""Add TrunkBreakout: through-table bridging FibreTrunk -> dcim.Cable.

PR B of the v0.2.0 cycle. Builds on 0003_fibretrunk.py.
"""
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0233_device_render_config_permission"),
        ("extras", "0138_customfieldchoiceset_choice_colors"),
        ("netbox_osp", "0003_fibretrunk"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrunkBreakout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("custom_field_data", models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ("fibre_range_start", models.PositiveSmallIntegerField()),
                ("fibre_range_end", models.PositiveSmallIntegerField()),
                ("description", models.CharField(blank=True, default="", max_length=200)),
                ("trunk", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="breakouts",
                    to="netbox_osp.fibretrunk",
                )),
                ("cable", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="osp_trunk_breakouts",
                    to="dcim.cable",
                )),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "Trunk Breakout",
                "verbose_name_plural": "Trunk Breakouts",
                "ordering": ("trunk", "fibre_range_start"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="trunkbreakout",
            constraint=models.CheckConstraint(
                condition=models.Q(fibre_range_start__gte=1),
                name="trunkbreakout_range_start_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="trunkbreakout",
            constraint=models.CheckConstraint(
                condition=models.Q(fibre_range_end__gte=models.F("fibre_range_start")),
                name="trunkbreakout_range_end_gte_start",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trunkbreakout",
            unique_together={("trunk", "cable"), ("trunk", "fibre_range_start")},
        ),
    ]
