# Generated by Django 6.0.4 on 2026-05-18.
"""Add polarity field to FibreTrunk.

v0.3.0 ecosystem-sprint PR #3. Records MPO/MTP polarity type
(Type A / B / C / D per TIA-568.3-D) on the FibreTrunk model.
Mirrors the existing trunk_type/status pattern: choices stay at
the application layer via `MpoPolarityChoices` rather than the DB
schema, so NetBox's custom-choice extensibility (ChoiceSet.key)
keeps working for operators who want to add their own polarity
variants. Blank is permitted for legacy data and non-MPO trunk
types (Ribbon, Loose-tube) where polarity is undefined.

Additive and non-destructive — existing FibreTrunk rows get the
empty-string default.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_osp", "0004_trunkbreakout"),
    ]

    operations = [
        migrations.AddField(
            model_name="fibretrunk",
            name="polarity",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
